# gitee-ssh-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitee-ssh-secret
  # 如果你的 Argo 运行在特定命名空间，记得指定
  namespace: argo
type: Opaque
stringData:
  # 这里使用stringData避免base64编码的麻烦
  # 将你的私钥内容粘贴在这里
  id_rsa: |
    {你的私钥id_rsa的内容}
    
  # SSH配置文件，StrictHostKeyChecking no是为了无需确认
  # gitee.com.，带一个点号是为了避免DNS解析问题，这个问题后面研究一下
  config: |
    Host gitee.com.
        HostName gitee.com.
        User git
        IdentityFile /root/.ssh/id_rsa
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null